[platformio]
default_envs = esp32

[env]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
build_flags =
  -Iinclude

[env:esp32]
build_flags =
  ${env.build_flags}
  -DZ_AXIS_DIAGNOSTIC_MODE=0

[env:esp32_diag]
build_flags =
  ${env.build_flags}
  -DZ_AXIS_DIAGNOSTIC_MODE=1
