; PlatformIO 项目配置文件
;
;   编译选项：编译标志、源码过滤规则
;   上传选项：上传串口、波特率及其他参数
;   库选项：依赖库与额外库目录
;   高级选项：额外脚本等
;
; 其他配置项可参考官方文档：
; https://docs.platformio.org/page/projectconf.html

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
